### ISSUE TITLE
Topics for discussion at the CTA Fall Forum Workshop 2020

### ISSUE THREAD

**Issue by wilaw** [cta-wave/technical-working-group#10]
We shall hold a workshop on Monday September 21st from 07:00- 11:00 PT to cover some of the decision points which require a deeper discussion than the regular TF meetings. 

Use this issue tracker to contribute discussion items. These will be collated by the TWG Chair before the meeting and converted in to a presentation deck to drive the agenda for the day.

For each item, please suggest a **title**, and provide **some background text** as well as **the decision to made or call-to-action**. Also state which task force you feel the work falls under.

**Comment by JohnRiv** [comment]
**Title:** Use Cases and Requirements for MSE v2
**Background:** The co-editors of MSE have put out a [call for feature requests, new unhandled use cases, and general
API improvements for MSE V2](https://lists.w3.org/Archives/Public/public-media-wg/2020Jun/0003.html). CTA WAVE did an analysis as the MSE v1 spec was being finalized and [submitted a document of use cases & requirements](https://www.w3.org/wiki/images/8/8c/Mse-eme-v2-use-cases-reqs-wave.pdf) to the W3C Media WG back then. 
**Call-to-Action:** Review the document and ensure that any previously identified use cases & requirements that are still important to WAVE have a corresponding issue in the [MSE Issues list](https://github.com/w3c/media-source/issues). If there is an issue, comment that it is still important to WAVE. If there is no issue, file one. Do the same for any other MSE-related issues that were not included in the original document.
**Task Force:** HATF

**Comment by krasimirkolarov** [comment]
Title: Finalizing CMAF-IF Web Landing page
Background: A small AdHoc group has worked for some time on selecting content, design and structure of the CMAF-IF Web page(s). At this point everything should be in place for the CMAF-IF group to discuss.
Call-to-Action: Consider the draft landing page(s), discuss on the reflector and aim to finalize at the meeting
Task Force: CMAF-IF

**Comment by krasimirkolarov** [comment]
Title: Discuss and finalizing the CMAF-IF Survey
Background: A large amount of work has gone into generating Survey questions and discussing both internally and with outside parties the mechanism(s) for ditributing the Survey
Call-to-Action: Agree on the content and mechanism for distribition and setup clear timeline for execution
Task Force: CMAF-IF

**Comment by krasimirkolarov** [comment]
Title: Discuss further opportunities for promotion of CTA WAVE tests and specs
Background: During the last few CMAF-IF meetings there have been discussions about opportunities for popularization of CTA WAVE's test suites and specifications. That included considering using Virtual Plugfests, Virtual MeetUps, making presentations at IBC, Mile High Video, Global Video Event (9/24), CES, NAB and others.
Call-to-Action: Continue this discussion and identify particular upcoming events and Action Items, including contact persons from the group to drive those.
Task Force: CMAF-IF

**Comment by haudiobe** [comment]
**Title**: Streaming functionalities for new codecs
**Background**: MPEG and ITU‐T have just completed two new codecs, namely VVC and EVC. In addition, other codecs are under development. Hence, there is the question on what would be needed on a functionality basis to advantageously add such codecs into the adaptive streaming functionalities. In the past we have been limited by what is supported on hardware devices and the streaming applications needed to deal with the functionalities and limitations of hardware devices, in particular to create “seamlessness”.
**External**: DASH-IF has started some initial work on this matter based on the attached work item [Work-Item-Proposal-Streaming-Next-Gen-Codecs-r3.pdf](https://github.com/cta-wave/technical-working-group/files/5197590/Work-Item-Proposal-Streaming-Next-Gen-Codecs-r3.pdf). It would be good if CTA WAVE can contribute to this.
**Task Force**: unknown
**Note**: I will almost certainly not be present as I am out on vacation.

**Comment by wilaw** [comment]
Title: DPCTF Test material preparation
Background: the following activities are under way

- Add a general description to wiki
- AVC/CFHD Options
    - Document here the generation details: https://github.com/cta-wave/Test-Content-Generation/wiki/CFHD-Test-Streams
    - Document all available test streams in data base: either part of DASH-IF or new instance. Separate entry point.
- HEVC Options
    - Create the documentation details for each CMAF Profile:
    - https://github.com/cta-wave/content-specification-task-force/wiki/Media-Profile:-CMAF-HEVC-UHD10-('cud1')
    - https://github.com/cta-wave/content-specification-task-force/wiki/Media-Profile:-CMAF-HEVC-HHD10-('chh1')
    - https://github.com/cta-wave/content-specification-task-force/wiki/Media-Profile:-CMAF-HEVC-HDR10-('chd1’)
    - Document all available test streams in data base
- AAC Options
    - Do the minimum here: https://github.com/cta-wave/Test-Content-Generation/wiki/CAAC-Test-Streams
- Encrypted Content
    - Do the minimum for cenc and cbcs, also using clear key content protection MPD
- Create a data base and front end for DASH and HLS playback

Task force: DPCTF

Notes: Rodolphe Fouquet from GPAC will participate in this slot. Request start time of 08h00 PT

**Comment by wilaw** [comment]
Title: GPAC tools and software and how this relates to CMAF
Background: GPAC have been engaged to complete work on the DASH IF test vectors. They are also the authors of mp4box, one of the leading open source packaging tools. The founder of GPAC  - Romain Bouqueau - will give a 20min talk on GPAC tools and software, with specail emphasis on how they relate to CMAF.
Task force: TWG
Note: to accommodate France time zone, request that this slot occur at 08h30 PT.

**Comment by wilaw** [comment]
Title: Common Media Client Data - CTA-5004
Background : CTA-5004 is the latest spec published by WAVE. This session will provide a quick over-view of what was developed and seek to encourage adoption by content distributors, player builders and CDNs. 
Task force: CMCD

**Comment by mbergman42** [comment]
Title: Audio Streaming and CMAF
Background : StreamGuys is a service provider of live and VOD streaming, podcasting delivery, and software-as-a-service toolsets for enterprise-level broadcast media organizations.  The company has experience with streaming audio in CMAF and supplies this technology to audio-only markets such as the radio broadcast market.  This CMAF-focused presentation will include issues, challenges and lessons learned from this experience.  (Note, this abstract is pending confirmation from the presenter.)
Task force: Content

**Comment by jpiesing** [comment]
Title: Testing a WAVE implementation
Background: We have some tests. We will have some test content but there's not a 1:1 relationship between the two. Some test content will be sufficient to play once from beginning to end (i.e. "Sequential Track Playback" - 8.2.). Some tests (like "Sequential Track Playback") will end up being run with several different streams for each media profile. Some tests may not have any particular dependency on the test content except that they should be run once for each media profile. What we have is a sparse matrix. We should decide how to document & describe this and plan to write a straw-man for AVC and HE-AAC. We need a name for the combination of test (HTML+JS) and media and a way of referencing a specific combination of test and media. 
This becomes what you might call a "test plan" for a WAVE implementation.
Task force; DPCTF

**Comment by technogeek00** [comment]
**Title:** Recommendations on splicing of CMAF presentations with differing features
**Background:** As part of the presentation splicing use case a primary scenario is the splicing together of CMAF presentations that may contain varied features, i.e. differences in available alternate video/audio/text renditions for language and/or role. The interoperability of these logical features is not a packaging issue, but a manifest creation issue and will need some guidelines / recommendations on how to pair / combine them together.
**Call-to-Action:** Discuss various changes that can occur and potentially highlight existing standards recommendations
**Task Force:** DASH-HLS Interop

**Comment by technogeek00** [comment]
**Title:** Interoperable Methods for Encryption Key Rotation
**Background:** As part of the encrypted media interop use case, key rotation has been identified as a complex issue due to the lack of interoperability of the scenario with various DRM systems. To provide an interop solution we need to understand the capabilities available for DRM systems and how they could translate into interoperable packaging.
**Call-to-Action:** Resurface any previous conversations / knowledge and discuss approaches that could be taken for defining interoperability
**Task Force:** DASH-HLS Interop
