### ISSUE TITLE
Issues to be addressed at IBC 2018 face-to-face workshop

### ISSUE THREAD

**Issue by wilaw** [cta-wave/technical-working-group#6]
Use this issue to add discussion topics to be addressed at the face-to-face meeting on Tuesday Sept 18th at Amsterdam Marriot Hotel. For each topic please provide
1. A title
2. Which TF this applies to - HATF, CSTF or DPCTF
3. background info on the subject & questions/proposals/solutions

**Comment by wilaw** [comment]
CSTF - cdv1
Conclude discussions on cdv1 - see https://standards.cta.tech/apps/org/workgroup/cstf/download.php/23750/Meeting%20Notes%20WAVE%20Content%20Spec%20TF%20Meeting_20180725.pdf

**Comment by wilaw** [comment]
CSTF - Approval process for media profiles

The approval process for media profiles (MP) has been documented and agreed upon in the WAVE CSTF. There are questions that need resolving, such as:


1. Are the requirements for a SDP distinct from those of an MP (section 2.2, of [WAVE MP]), or is it simply a matter of updating the language to mention both MP and SDP?
2. A SDP is applied to MPs, and a client which only understands the underlying MP and not the SDP should perform normally. This is a device playback consideration, but is it also a content spec consideration?
3. An SDP (SEI message) does have MSE requirements, which should be captured in the binding specification. Is there generic language we can place in WAVE regarding this, or must it be captured individually in each SDP CMAF binding spec?

**Comment by wilaw** [comment]
DPCTF & HATF
Should the issues identified for the User Agent Integration spec be implemented as an extension of the DPCTF spec and test?
Identified issues are:

-     Accuracy of value returned by HTMLMediaElement.currentTime
-     Requirement to launch first page of Web App in full screen mode with no browser chrome
-     Combinations of various W3C APIs - E.g. media fragment URLs with MSE
-     MSE buffering and timing
-     Root certificates for TLS
-     Number of simultaneous HTTP connections & timing
-     Size & persistence of cookies and data stored by web storage API
-     URL length
-     Graphics resolution used for rendering browser UI & relation to video resolution
-     Still image formats
-     Remote keys / key events
-     Formatting of HTTP User Agent string
-     Application loading & transition times
-     Minimum graphics performance (decoding & rendering full screen images, CSS3 animations, etc)
-     Accept cookies of a certain minimum size

![image](https://user-images.githubusercontent.com/2762250/45341892-0f642580-b551-11e8-8766-1950cae372a6.png)

**Comment by wilaw** [comment]
Should HATF or DPCTF own User Agent issues such as cookies and key testing ?

**Comment by wilaw** [comment]
How to submit modified test content back to WAVE and a means to confirm it meets the spec(s).

Which TFs have scope over test content?
I could see this being pretty much a DPCTF topic.  I’ve added CSTF because the format of test content needs to be compliant with CSTF specifications. So it seems DPCTF would be responsible for identifying requirements for test content, and CSTF somewhat involved in confirming that the content meets the Content spec. 

2. What is the process for approving test content in the first place?
The AI refers to modified content, but before we worry about mods we should have a process in place to vet the original test material.
I assume test content will need to be run through the Content Validator, when it is ready.  However, I also assume we will have intentionally non-compliant content intended to trigger certain behaviors (error checking) in players?  Or not?
We need people, ideally technically astute volunteers, to vet content according to a process.  This implies some carefully crafted requirements for each item.

**Comment by wilaw** [comment]
DPCTF - walk through of current spec 0.5.8

**Comment by wilaw** [comment]
License terms for WAVE test Content

Do we need separate license for source content versus encoded content?
We cannot use BBB with Creative Commons No Derivative license?

Looking at a Creative Commons No Derivative Works + Attribution license.
Details: https://creativecommons.org/choose 
The ND license: http://creativecommons.org/licenses/by-nd/4.0/ 
Considering selecting the following terms:
Attribution 
You must give appropriate credit, provide a link to the license, and indicate if changes were made. 
You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
NoDerivatives 
If you remix, transform, or build upon the material, you may not distribute the modified material.
No additional restrictions 
You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

**Comment by jpiesing** [comment]
Thomas's input about cmf2 (email of 27th August).

**Comment by wilaw** [comment]
DPCTF: MSE related issues

- Issues to be filed for MSEv2
- Byte Stream format for CTA WAVE/CMAF

**Comment by wilaw** [comment]
DPCTF: Status of Specification and Open issues

- Content Options and Device Playback – Problem statement and where to document  refer to document and decide how to progress the document
- Status Report and resulting actions for Media Profile proponents

**Comment by wilaw** [comment]
DPCTF: Proposed test process
