### ISSUE TITLE
Issues to be addressed at the CTA Fall Forum 2019 face-to-face workshop.

### ISSUE THREAD

**Issue by wilaw** [cta-wave/technical-working-group#8]
The WAVE project will hold a face-to-face workshop on in Los Angeles on Monday Sept 23 from 9-12 and 1:30-5pm and Tuesday 9-12. Use this issue tracker to contribute discussion items. These will be collated by the TWG Chair before the meeting and converted in to a presentation deck to drive the agenda for the day. 

For each item, please suggest a title, and provide some background text as well as the decision to made or call-to-action. Also state which task force you feel the work falls under.

**Comment by wilaw** [comment]
Chris Cunningham of Google, author of the Media Capabilities specification, has been invited to join the meeting remotely to discuss  “Intended capability additions to the Media Capability API around codec switching and smooth transitions”. I am waiting for confirmation from him as to day and time.

**Comment by wilaw** [comment]
W3C Privacy Interest Group have an interest in reducing API surface to reduce fingerprinting. How does this affect Media Capabilities as well as our general architecture of a web-based platform with capability discovery at its core?

**Comment by wilaw** [comment]
Harmonizing media profiles between CSTF, ATSC and 3GPP

**Comment by wilaw** [comment]
Coordination between CSTF and ATSC

**Comment by haudiobe** [comment]
> Harmonizing media profiles between CSTF, ATSC and 3GPP

This should also include DVB

**Comment by haudiobe** [comment]
CMAF byte stream format draft

**Comment by haudiobe** [comment]
EMSG Processing Requirements in DPC

**Comment by haudiobe** [comment]
Consistent playback tests and Manifest signaling for encrypted content

**Comment by haudiobe** [comment]
DPC Version 2 - what is in and what is out?

**Comment by wilaw** [comment]
Pick and discuss HATF https://github.com/w3c/webmediaapi/issues/199 

On Media Source Extensions, we do not limit this to the ISO BMFF byte stream format. Is this intentional? Or said differently, should it not mandate the support of ISO BMFF byte stream format
On Web Audio API:
o	Has anyone checked how the Web Audio API interacts with our audio profiles?
o	Does W3C has tests for the Web Audio API that may be combined reused for DPCTF tests?

**Comment by JohnRiv** [comment]
Upgrading the AWS instance that https://webapitests2018.ctawave.org/ runs on to reduce timeouts

**Comment by JohnRiv** [comment]
HATF https://github.com/w3c/webmediaapi/issues/211

During our initial discussion on this topic, I believe we left this as we should either add some technical details around handling a `Cue` or explicitly agree to not include any details.

**Comment by johnluther** [comment]
HATF w3c/webmediaapi#219

Discuss standing up https://webapitests2019.ctawave.org/ server to prepare for the updated test set. Initially can be stood up with the 2018 tests as placeholder.

**Comment by wilaw** [comment]
From Stockhammer - my suggestion is that we create the following:

- Create a set of user stories – at the meeting I heard the one from MainConcept (single encoding and packaging), Unified Streaming (single ingest), Akamai (single distribution), etc.
- For each of the user stories, the story is told from the perspective of the area what is done today and what are the problems until now. Then we describe how CMAF/CTA WAVE/others help solving the problems
- The user story should then include a very clear set of references to specifications, test tools and how the work flow of the CMAF user can be improved
- These stories are published as blogs, associated with names and companies behind it.

**Comment by JohnRiv** [comment]
**Title:** Type 1 Playback & W3C Standards
**TF:** DPCTF

When I gave an update on CTA WAVE during the W3C Media & Entertainment Interest Group meeting at TPAC, Type 1 Playback (https://github.com/cta-wave/device-playback-task-force/issues/31) caught the attention of the group. Those present stated if there is anything from a W3C standards perspective that could help with that, they'd be happy to discuss.

This may be more of a "for awareness" type item than an actual issue to address, but either way I feel it is worth mentioning at the F2F.

**Comment by wilaw** [comment]
Review proposals for UI for Test Suite interface

**Comment by JohnRiv** [comment]
**Title:** Web Media API Test Suite updates to support Web Platform Tests
**TF:** HATF

There is an [open PR on the web-platform-tests RFCs repo](https://github.com/web-platform-tests/rfcs/pull/23) to work through how we could upstream the WMAS2018 test suite changes back to the [web-platform-tests project](https://github.com/web-platform-tests/wpt). The comments in that PR explain the initial set of asks from the WPT team. I'd like to understand our plan to address those comments and also explore how we can best build the WMAS tests in a way so that they can easily upstream back to WPT what is useful, keep separate what is not useful to WPT, and ease the ability to pull in the latest from WPT as we make future updates.

**Comment by JohnRiv** [comment]
**Title:** Shorten lead time between Web Media API Snapshot updates and subsequent Test Suite updates
**TF:** HATF

Ideally, WMAS test suite changes would be made at the same time updates to the WMAS spec are committed to GitHub (before the annual Snapshot is even officially published). In reality the time gap between the two is months. How can we bring those closer together?
