### ISSUE TITLE
Topics for discussion at the CTA Spring Forum 2020

### ISSUE THREAD

**Issue by johnluther** [cta-wave/technical-working-group#9]
The WAVE Project will hold a workshop during the virtual [CTA Spring Forum](https://www.cta.tech/Events/Technology-and-Standards-Spring-Forum) on Monday, May 11th from 10 am - 4 pm Eastern US time (connectivity logistics TBD).

Use this issue to contribute discussion items. These will be collated by the TWG Chair and converted in to a presentation deck to drive the agenda.

For each topic please provide:

1. A title
2. Which Task Force the issue applies to - HATF, CSTF or DPCTF
3. Brief background info on the subject as well as questions and desired outcomes, if known

**Comment by johnsim** [comment]
Title: Move the DASH-HLS Interop Spec to a TWG ad hoc group
Task Force: CSTF
Background: The Content Specification Task Force arguably is not the right group to manage this specification. There are inputs to this spec from the task force, as it relates to constraining CMAF media segments, but the work is becoming one of aligning DASH and HLS.

**Comment by johnsim** [comment]
Title: Move CSTF meetings to an "as needed" basis
Task Force: CSTF
Background: If the DASH-HLS Interop Spec is moved to a TWG ad hoc group the sole work of the CSTF would become updating the WAVE Content Spec with new media profiles. This would not require a meeting every two weeks. Standing meetings are a resource hog.

**Comment by johnsim** [comment]
Title: Create an TWG ad hoc Group focused solely on Media Capabilities
Task Force: CSTF, HATF, DPCTF
Background: Insufficient attention is being paid to HTML5 Media Capabilities, which is where the CMAF media profiles and the HTML5 API interface meet. It is falling in the space between CSTF and HATF, and impacting DPCTF. There will be a polyfill JavaScript library which will take the 4cc code corresponding to the media profile and translate this into the correct video configuration query through HTML5 media capabilities. WAVE needs to ensure this will be the case.

**Comment by johnsim** [comment]
Title: Create a liaison with HbbTV to develop a virtual plug-fest model 
Task Force: CSTF, DPCTF
Background: HbbTV has a highly developed model for plug-fest testing. The proof of the pudding is in the eating, which is to say the proof of the specification is in the testing. Plug-fests are how we will prove the value of WAVE. This topic has been discussed in CSTF and DPCTF, as well as in the CMAF IF, but it needs to be owned by someone.

**Comment by johnluther** [comment]
Thanks for these, @johnsim .

**Comment by johnsim** [comment]
Title: DRM interoperable CMAF Packaging for DASH and HLS
Task Force: DASH-HLS Interop Ad Hoc Group
Background: See topics raised in the Joint CTA-WAVE/DASH IF CPS meeting - both in terms of 'saio'/'saiz'/'senc' packaging of DRM metadata as well as key rotation using 'pssh' boxes in the 'moof' and how it is handled by DASH and HLS clients.

**Comment by johnluther** [comment]
These two topics won't need F2F discussion: 

- Move DASH-HLS Interop Spec to TWG ad hoc group was approved in April TWG meeting
- Move CSTF meetings to "as needed" basis was approved in April Steering Committee meeting
